routes/web.php
<?php
use App\Http\Middleware\Checker;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'home']);

Route::resource('users', 'UsersController', ['middleware' => 'checker']);
Route::resource('roles', 'RolesController', ['middleware' => ['checker', 'web']]);
Route::resource('permissions', 'PermissionsController', ['middleware' => ['checker', 'web']]);

Auth::routes();

Route::get('/home', 'DashboardController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout');

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    //
}

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PermissionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/permissions/index.blade.php
@extends('layouts.main')

@section('content')
    {!! $content !!}
@endsection

resources/views/permissions/index_content.blade.php
<div class="row-fluid">
    {!! Html::link(route('roles.create'),'Add new role',['class' => 'btn btn-success']) !!}
    {!! Html::link(route('permissions.create'),'Add new permission',['class' => 'btn btn-success']) !!}
</div>

resources/views/permissions/permission_form.blade.php
<div class="row-fluid">
    <div class="span10">
        <div class="widget-box">
            <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>New Item creating</h5>
            </div>
            <div class="widget-content nopadding">

                {!! Form::open(['class' => 'form-horizontal' , 'method' => 'post', 'action' => 'RolesController@store', 'enctype' => 'multipart/form-data'])  !!}
                <form action="#" method="get" class="form-horizontal">
                <div class="control-group">
                    {!! Form::label('Name', null, ['class' => 'control-label']); !!}
                    <div class="controls">
                        {!! Form::text('name', null, ['class' => 'span11', 'style' => 'padding: 5px']); !!}
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
                </form>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>